Update README.md, create_ap, and create_ap.conf - "0.4.8" to "0.4.9" Update with: https://github.com/lakinduakash/linux-wifi-hotspot/     /src/scripts/ (README.md, bash_completion, create_ap, create_ap.conf)

diff --git a/create_ap b/create_ap
--- a/create_ap
+++ b/create_ap
@@ -14,7 +14,7 @@
 #    dnsmasq
 #    iptables
 
-VERSION=0.4.8
+VERSION=0.4.9
 PROGNAME="$(basename $0)"
 
 # make sure that all command outputs are in english
@@ -63,6 +63,11 @@ usage() {
     echo "                          back to managed"
     echo "  --mac <MAC>             Set MAC address"
     echo "  --dhcp-dns <IP1[,IP2]>  Set DNS returned by DHCP"
+    echo "  --dhcp-hosts <H1[,H2]>  Add list of dnsmasq.conf 'dhcp-host=' values"
+    echo "                          If ETC_HOSTS=1, it will use the ip addresses for the named hosts in that /etc/hosts."
+    echo "                          Othwise, the following syntax would work --dhcp-hosts \"host1,192.168.12.2 host2,192.168.12.3\""
+    echo "                          See https://github.com/imp/dnsmasq/blob/770bce967cfc9967273d0acfb3ea018fb7b17522/dnsmasq.conf.example#L238"
+    echo "                          for other valid dnsmasq dhcp-host parameters."
     echo "  --daemon                Run create_ap in the background"
     echo "  --pidfile <pidfile>     Save daemon PID to file"
     echo "  --logfile <logfile>     Save daemon messages to file"
@@ -640,6 +645,7 @@ GATEWAY=192.168.12.1
 WPA_VERSION=2
 ETC_HOSTS=0
 ADDN_HOSTS=
+DHCP_HOSTS=
 DHCP_DNS=gateway
 NO_DNS=0
 NO_DNSMASQ=0
@@ -672,7 +678,7 @@ REDIRECT_TO_LOCALHOST=0
 CONFIG_OPTS=(CHANNEL GATEWAY WPA_VERSION ETC_HOSTS DHCP_DNS NO_DNS NO_DNSMASQ HIDDEN MAC_FILTER MAC_FILTER_ACCEPT ISOLATE_CLIENTS
              SHARE_METHOD IEEE80211N IEEE80211AC IEEE80211AX HT_CAPAB VHT_CAPAB DRIVER NO_VIRT COUNTRY FREQ_BAND
              NEW_MACADDR DAEMONIZE DAEMON_PIDFILE DAEMON_LOGFILE DNS_LOGFILE NO_HAVEGED WIFI_IFACE INTERNET_IFACE
-             SSID PASSPHRASE USE_PSK ADDN_HOSTS)
+             SSID PASSPHRASE USE_PSK ADDN_HOSTS DHCP_HOSTS)
 
 FIX_UNMANAGED=0
 LIST_RUNNING=0
@@ -1000,7 +1006,26 @@ send_stop() {
 write_config() {
     local i=1
 
-    if ! eval 'echo -n > "$STORE_CONFIG"' > /dev/null 2>&1; then
+    # If using pkexec, evaluate permissions before writing.
+    #   However, the /etc/create_ap.conf
+    #   location is excepted.
+    if [[ "$STORE_CONFIG" != "/etc/create_ap.conf" && $PKEXEC_UID ]]; then
+        if [ -e "$STORE_CONFIG" ]; then
+            if ! pkexec --user "$(id -nu $PKEXEC_UID)" test -w "$STORE_CONFIG"; then
+                echo "ERROR: 1 $(id -nu $PKEXEC_UID) has insufficient permissions to write to config file $STORE_CONFIG"
+                exit 1
+            fi
+        elif ! pkexec --user "$(id -nu $PKEXEC_UID)" test -w "$(dirname "$STORE_CONFIG")"; then
+            echo "ERROR: 2 $(id -nu $PKEXEC_UID) has insufficient permissions to write to config file $STORE_CONFIG"
+            exit 1
+        fi
+        # Assume that the user is making a conf file in a directory they normally
+        # have control over, and keep permissions strictly private. (i.e. they will
+        # need to run create_ap directly with sudo in order to write to, say, /etc/create_ap2.conf)
+        touch "$STORE_CONFIG"
+        chown "$(id -nu $PKEXEC_UID):$(id -ng $PKEXEC_GID)" "$STORE_CONFIG"
+        chmod 600 "$STORE_CONFIG"
+    elif ! eval 'echo -n > "$STORE_CONFIG"' > /dev/null 2>&1; then
         echo "ERROR: Unable to create config file $STORE_CONFIG" >&2
         exit 1
     fi
@@ -1050,7 +1075,7 @@ read_config() {
         if is_config_opt "$opt_name" ; then
             eval $opt_name="\$opt_val"
         else
-            echo "WARN: Unrecognized configuration entry $opt_name" >&2
+            echo "WARN: Unrecognized configuration entry. Please check your config file." >&2
         fi
     done < "$LOAD_CONFIG"
 }
@@ -1074,7 +1099,7 @@ for ((i=0; i<$#; i++)); do
     fi
 done
 
-GETOPT_ARGS=$(getopt -o hc:w:g:de:nm: -l "help","hidden","hostapd-debug:","hostapd-timestamps","redirect-to-localhost","mac-filter","mac-filter-accept:","isolate-clients","ieee80211n","ieee80211ac","ieee80211ax","ht_capab:","vht_capab:","driver:","no-virt","fix-unmanaged","country:","freq-band:","mac:","dhcp-dns:","daemon","pidfile:","logfile:","dns-logfile:","stop:","list","list-running","list-clients:","version","psk","no-haveged","no-dns","no-dnsmasq","mkconfig:","config:" -n "$PROGNAME" -- "$@")
+GETOPT_ARGS=$(getopt -o hc:w:g:de:nm: -l "help","hidden","hostapd-debug:","hostapd-timestamps","redirect-to-localhost","mac-filter","mac-filter-accept:","isolate-clients","ieee80211n","ieee80211ac","ieee80211ax","ht_capab:","vht_capab:","driver:","no-virt","fix-unmanaged","country:","freq-band:","mac:","dhcp-dns:","daemon","pidfile:","logfile:","dns-logfile:","stop:","list","list-running","list-clients:","version","psk","no-haveged","no-dns","no-dnsmasq","mkconfig:","config:","dhcp-hosts:" -n "$PROGNAME" -- "$@")
 [[ $? -ne 0 ]] && exit 1
 eval set -- "$GETOPT_ARGS"
 
@@ -1128,6 +1153,11 @@ while :; do
         -e)
             shift
             ADDN_HOSTS="$1"
+            shift
+            ;;
+        --dhcp-hosts)
+            shift
+            DHCP_HOSTS="$1"
             shift
             ;;
         -n)
@@ -1796,6 +1826,13 @@ EOF
     [[ -n "$MTU" ]] && echo "dhcp-option-force=option:mtu,${MTU}" >> $CONFDIR/dnsmasq.conf
     [[ $ETC_HOSTS -eq 0 ]] && echo no-hosts >> $CONFDIR/dnsmasq.conf
     [[ -n "$ADDN_HOSTS" ]] && echo "addn-hosts=${ADDN_HOSTS}" >> $CONFDIR/dnsmasq.conf
+    if [[ -n "$DHCP_HOSTS" ]]; then
+        for HOST in $DHCP_HOSTS; do
+            echo "dhcp-host=${HOST}" >> $CONFDIR/dnsmasq.conf
+        done
+    fi
+
+
     if [[ -n "$DNS_LOGFILE" ]]; then
         cat << EOF >> $CONFDIR/dnsmasq.conf
 log-queries
